#!/bin/bash
#
# Description : helper
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

sudo sh -c 'printf "\033c" > /dev/tty1'

if ! dpkg -s "dialog" >/dev/null 2>&1; then
	sudo sh -c 'echo "Installing dependency dialog ..." > /dev/tty1'
	sudo apt update && sudo apt install -y dialog
fi

if ! dpkg -s "unzip" >/dev/null 2>&1; then
	sudo sh -c 'echo "Installing dependency unzip ..." > /dev/tty1'
	sudo apt update && sudo apt install -y unzip
fi

if ! dpkg -s "curl" >/dev/null 2>&1; then
	sudo sh -c 'echo "Installing dependency curl ..." > /dev/tty1'
	sudo apt update && sudo apt install -y curl
fi

if ! dpkg -s "wget" >/dev/null 2>&1; then
	sudo sh -c 'echo "Installing dependency wget ..." > /dev/tty1'
	sudo apt update && sudo apt install -y wget
fi

if ! dpkg -s "libevdev2" >/dev/null 2>&1; then
	sudo sh -c 'echo "Installing dependency libevdev2 ..." > /dev/tty1'
	sudo apt update && sudo apt install -y libevdev2
fi