#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Amazon Luna ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/Amazon.Luna.sh'
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/weston.zip'
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/chromium.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o weston.zip -d ../
unzip -qq -o chromium.zip -d ../

mv Amazon.Luna.sh ../Amazon\ Luna.sh

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf weston.zip
rm -rf chromium.zip

dialog --backtitle "System" --infobox "\nEnjoy! ..." 6 55 > /dev/tty1
sleep 5