#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nInstalling dependencies ..." 5 55 > /dev/tty1
sudo apt update && sudo apt install -y weston wayland-protocols libevent-2.1-6 libwebpdemux2 xwayland

if ! grep "WAYLAND_DISPLAY" /etc/environment > /dev/null
then
  sudo sh -c 'echo "DISPLAY=:0" >> /etc/environment'
  sudo sh -c 'echo "XDG_RUNTIME_DIR=/run/user/1002" >> /etc/environment'
  sudo sh -c 'echo "WAYLAND_DISPLAY=/run/user/1002/wayland-0" >> /etc/environment'
fi

dialog --backtitle "System" --infobox "\nDownloading Google Stadia (Might take a while) ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/google-stadia.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o google-stadia.zip -d ../
unzip -qq -o ../weston.zip -d ../

cp ../weston/weston.ini ~/.config/
cp -r ../weston/chromium/chrome ~/

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf google-stadia.zip
rm -rf ../weston.zip

dialog --backtitle "System" --infobox "\nEnjoy! ..." 6 55 > /dev/tty1
sleep 5