#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#
version=1.1.4

export TERM=linux
sudo chmod 666 /dev/tty1

StreamingMenu() {
	cmd=(dialog --clear --backtitle "AnberPorts" --title "[ Streaming ]" --menu "Select application from the list:" "15" "56" "15")

	options=(
		Back "Back to main menu"
		Moonlight-Embedded "Gamestream client for embedded systems"
		Nvidia-GeForce-NOW "BETA: GeForce NOW is the brand used by Nvidia for its cloud gaming service"
		Google-Stadia "BETA: Stadia is a cloud gaming service developed and operated by Google"
		Amazon-Luna "BETA: Amazon Luna is a cloud gaming platform developed and operated by Amazon"
	)

    choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)
   	bash ./scripts/streaming/${choices[0]}
}

MultimediaMenu() {
	cmd=(dialog --clear --backtitle "AnberPorts" --title "[ Multimedia ]" --menu "Select application from the list:" "15" "56" "15")

	options=(
		Back "Back to main menu"
		Kodi "Free and open-source media player software"
	)

    choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)
   	bash ./scripts/multimedia/${choices[0]}
}

GamesMenu() {
	cmd=(dialog --clear --backtitle "AnberPorts" --title "[ Games ]" --menu "Select game from the list:" "15" "56" "15")

	options=(
		Back "Back to main menu"
		Half-Life "Gordon Freeman must exit Black Mesa"
		Counter-Strike "Multiplayer first-person shooter video game"
		Half-Life-Blue-Shift "Blue Shift is an expansion pack for the first-person shooter video game Half-Life"
		Shadow-Warrior "Shadow Warrior is shooter video game"
		Quake1 "ID Software's Quake saga"
		Quake2 "ID Software's Quake saga"
		Quake3 "ID Software's Quake saga"
		Eduke32 "Duke Nukem 3D is a fps game"
		Flashback "The Quest for Identity - Delphine Software"
		CannonBall "The Enhanced OutRun Engine"
		Cave-Story "2004 Metroidvania platform-adventure game"
		Diablo1 "Beneath the town of Tristram, the player journeys"
		Diablo2 "Diablo II is an action role-playing hack-and-slash computer video game"
		Doom1 "1993 first-person shooter game developed by id Software"
		Doom2 "First-person shooter game by id Software"
		Keen "Series of side-scrolling platform video games"
		Rick-Dangerous "Platform game developed by Core Design"
		Wolfenstein-3D "First-person shooter video game developed by id Software"
		Blood "First-person shooter video game"
		Exhumed "First-person shooter"
		NAM "NAM, sold under the name Napalm, first-person shooter video game"
		Redneck-Rampage "1997 first-person shooter game"
		Redneck-Rampage-Rides-Again "Redneck Rampage Rides Again is a video game developed by Xatrix Entertainment"
		World-War-II-GI "first-person shooter video game set during the events of World War II"
		Sonic-Robo-Blast-2 "Fan-made, free Sonic-themed game using a modified version of the Doom engine"
		Alien-vs-Predator "2010 first-person shooter video game"
		Prince-of-Persia "Video game franchise created by Jordan Mechner"
		The-Ur-Quan-Masters "The Ur-Quan Masters is the sequel to Star Control"
		The-Clue "1994 video game inspired by the 1986 game They Stole a Million"
		Spelunky "Unique platformer with randomized levels that offer a challenging new experience"
		AM2R "Action-adventure game developed by Argentinian programmer Milton Guasti"
		System-Shock "1994 first-person action-adventure video game"
		Jedi-Academy "First- and third-person shooter video game"
	)

    choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)
   	bash ./scripts/games/${choices[0]}
}

ExitMenu() {
	pgrep -f oga_controls | sudo xargs kill -9
	sudo systemctl restart emulationstation
}

UpdateMenu() {
	source ./scripts/helper

	dialog --backtitle "System" --infobox "\nDownloading latest release of AnberPorts ..." 5 55 > /dev/tty1
	curl -s https://api.github.com/repos/krishenriksen/AnberPorts/releases/latest | grep browser_download_url | cut -d '"' -f 4 | wget -qi -

	dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
	unzip -qq -o AnberPorts.zip -d ../

	dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
	rm -rf AnberPorts.zip

	dialog --backtitle "System" --infobox "\nPlease launch AnberPorts again and enjoy ..." 5 55 > /dev/tty1
	sleep 5

	ExitMenu
}

source ./scripts/helper

#
# Joystick controls
#
sudo ./oga_controls &

#
# Version management
#
latest=`wget -qO- https://api.github.com/repos/krishenriksen/AnberPorts/releases/latest | grep tag_name | cut -d '"' -f 4`
update="Using latest version"

if [ $latest \> $version ]; then
  update="New version available!"
fi

#
# Main menu
#
while true; do
	cmd=(dialog --clear --backtitle "AnberPorts $version" --title " [ Main Menu ] " --menu "You can use UP/DOWN on the D-pad and A to select:" "15" "56" "15")

	options=(
		Games "Install game ports"
		Multimedia "Install multimedia apps"
		Streaming "Install game streaming"
		Update "$update"
		Exit "Exit to emulationstation"
	)

	choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)

	for choice in $choices; do
		case $choice in
			Games) GamesMenu ;;
			Multimedia) MultimediaMenu ;;
			Streaming) StreamingMenu ;;
			Update) UpdateMenu ;;
			Exit) ExitMenu ;;
		esac
	done
done
