#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Blood ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/blood.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o blood.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf blood.zip

mkdir -p ~/.config/nblood
mv ../Blood/nblood.cfg ~/.config/nblood/
mv ../Blood/settings.cfg ~/.config/nblood/

dialog --backtitle "System" --infobox "\nPlease copy games files to your Blood directory! ..." 6 55 > /dev/tty1
sleep 5
