#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Diablo 2 ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/weston.zip'
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/diablo2.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o weston.zip -d ../
unzip -qq -o diablo2.zip -d ../

mkdir -p ~/.config/OpenDiablo2
cp ../diablo2/config.json ~/.config/OpenDiablo2/

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf weston.zip
rm -rf diablo2.zip

dialog --backtitle "System" --infobox "\nPlease copy LoD v1.13c game files to your diablo2 directory! ..." 6 55 > /dev/tty1
sleep 5