#!/bin/bash
#
# Description : Doom 1
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Doom 1 ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/doom1.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o doom1.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf doom1.zip

dialog --backtitle "System" --infobox "\nPlease copy 'Doom.wad' to your doom1 directory! ..." 6 55 > /dev/tty1
sleep 5