#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Exhumed / PowerSlave ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/exhumed.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o exhumed.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf exhumed.zip

mkdir -p ~/.config/rednukem
mv ../Exhumed/rednukem.cfg ~/.config/rednukem/
mv ../Exhumed/settings.cfg ~/.config/rednukem/

dialog --backtitle "System" --infobox "\nPlease copy games files to your Exhumed directory! ..." 6 55 > /dev/tty1
sleep 5