#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Star Wars Jedi Knight: Jedi Academy ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/OpenJK/releases/download/1.0.0/jediacademy.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o jediacademy.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf jediacademy.zip

dialog --backtitle "System" --infobox "\nPlease copy *.pk3 files to your JediAcademy/base directory! ..." 6 55 > /dev/tty1
sleep 5