#!/bin/bash
#
# Description : Commander Keen
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Commander Keen ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/keen.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o keen.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf keen.zip

dialog --backtitle "System" --infobox "\nPlease copy 'keen' folders to your cgenius/games directory! ..." 6 55 > /dev/tty1
sleep 5