#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading NAM ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/nam.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o nam.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf nam.zip

mkdir -p ~/.config/rednukem
mv ../NAM/rednukem.cfg ~/.config/rednukem/
mv ../NAM/settings.cfg ~/.config/rednukem/

dialog --backtitle "System" --infobox "\nPlease copy games files to your NAM directory! ..." 6 55 > /dev/tty1
sleep 5