#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Prince of Persia ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/sdlpop.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o sdlpop.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf sdlpop.zip

dialog --backtitle "System" --infobox "\nEnjoy! ..." 6 55 > /dev/tty1
sleep 5