#!/bin/bash
#
# Description : quake2
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Quake 2 ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/yquake2-rg351p/releases/download/1.0.0/quake2.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o quake2.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf quake2.zip

dialog --backtitle "System" --infobox "\nPlease copy '*.pak' to your quake2/baseq2 directory! ..." 6 55 > /dev/tty1
sleep 5