#!/bin/bash
#
# Description : Quake 1
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Quake 1 ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/quake1.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o quake1.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf quake1.zip

dialog --backtitle "System" --infobox "\nPlease copy 'PAK0.PAK' to your quake1 directory! ..." 6 55 > /dev/tty1
sleep 5