#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Redneck Rampage ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/redneck-rampage.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o redneck-rampage.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf redneck-rampage.zip

mkdir -p ~/.config/rednukem
mv "../Redneck Rampage/rednukem.cfg" ~/.config/rednukem/
mv "../Redneck Rampage/settings.cfg" ~/.config/rednukem/

dialog --backtitle "System" --infobox "\nPlease copy game files to your Redneck Rampage directory! ..." 6 55 > /dev/tty1
sleep 5