#!/bin/bash
#
# Description : Rick Dangerous
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading Rick Dangerous ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/rick-dangerous.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o rick-dangerous.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf rick-dangerous.zip

dialog --backtitle "System" --infobox "\nEnjoy! ..." 6 55 > /dev/tty1
sleep 5