#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading System Shock ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/systemshock/releases/download/1.0.0/systemshock.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o systemshock.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf systemshock.zip

dialog --backtitle "System" --infobox "\nPlease copy game 'data' folder to your systemshock/res directory! ..." 6 55 > /dev/tty1
sleep 5