#!/bin/bash
#
# Author      : Kris Henriksen <krishenriksen.work@gmail.com>
#

source ./scripts/helper

dialog --backtitle "System" --infobox "\nDownloading World War II GI ..." 5 55 > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/world-war-ii-gi.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
unzip -qq -o world-war-ii-gi.zip -d ../

dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
rm -rf world-war-ii-gi.zip

mkdir -p ~/.config/rednukem
mv "../World War II GI/rednukem.cfg" ~/.config/rednukem/
mv "../World War II GI/settings.cfg" ~/.config/rednukem/

dialog --backtitle "System" --infobox "\nPlease copy game files to your World War II GI directory! ..." 6 55 > /dev/tty1
sleep 5